### ISSUE TITLE
ERROR The "angular" preset does not export a function.

### ISSUE THREAD

**Issue by patshologram** [release-it/conventional-changelog#74]
Hello,

we updated our dependencies and since then we get the following error:
> ERROR The "angular" preset does not export a function. Maybe you are using an old version of the preset. Please upgrade.

The versions we use
```    
   "@release-it/conventional-changelog": "^7.0.1",
   "release-it": "^16.1.5",
```

The plugin settings we use (as described in [Configuration]( https://github.com/release-it/conventional-changelog#configuration))
```
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": {
        "name": "angular"
      },
      "infile": "CHANGELOG.md"
    }
  },
```

Changing the `name` to `conventionalcommits` let us complete the release, so the setup in general seems to be fine but the preset with `name: angular` seems to be outdated(?).

**Comment by silversonicaxel** [comment]
More info here about the same issue.

This is my current `.release-it.yaml`

```
plugins:
  '@release-it/conventional-changelog':
    preset: angular
    infile: CHANGELOG.md
```

It works with **v7.0.0** but it doesn't work with **v7.0.1**.

And the same behaviour occurs with this configuration:

```
plugins:
  '@release-it/conventional-changelog':
    preset:
      name: angular
    infile: CHANGELOG.md
```
